### ISSUE TITLE
出一个新的版本

### ISSUE THREAD

**Issue by Reversedeer** [Monarchdos/nonebot_plugin_cloudsign#1]
能不能出一个本地的版本，这个插件用法和zdy插件及其相似qwq
但是我觉得出一个本地的对于用户修改和增加新功能还是比较好的

**Comment by Monarchdos** [comment]
目前所有的逻辑代码都是在云端的，本地版后面会考虑写的😋
云签到的特点之一就是数据不可以被修改，所有用户公平✌

**Comment by Reversedeer** [comment]
好的，非常期待看到本地的源码
这个插件与我之前使用的易语言开发的自定义插件非常像，作者是来自这里的灵感吗

**Comment by Monarchdos** [comment]
这个插件我在酷q还在的时候就用易语言写过本地版的并在社区有发布，现在将其转到云端进行开发了🥰

**Comment by Reversedeer** [comment]
good luck
