### ISSUE TITLE
小提议

### ISSUE THREAD

**Issue by nansou520** [Monarchdos/nonebot_plugin_cloudsign#11]
这个东西,非常能使群友上瘾
不知道其他机器人那边这个插件热度怎么样,我这是玩疯了
我建议多弄点数据统计,例如:
GDP统计(差不多这个意思))))
机器人热度(触发本插件的频率)统计
转账统计
等等
好的我知道这些很废时间
我觉得可能,应该,大概,会提升一下群友的好胜心吧()()()()

**Comment by Monarchdos** [comment]
相关数据也都有统计，后续会逐步开发数据展示功能
