### ISSUE TITLE
部分新用户第一次签到会显示0级 且无法使用其他功能

### ISSUE THREAD

**Issue by Ant1816** [Monarchdos/nonebot_plugin_cloudsign#13]
签到成功✅
签到获得 27 积分💲
连签一周额外获得 50 积分
[Lv.0] 默默无闻
现有积分: 
累计签到:  天
连续签到:  天
签到顺序: 36
2024-11-16

**Comment by Monarchdos** [comment]
修复了已经，发送"#兑换 2024111416"可领取补偿积分。
