### ISSUE TITLE
命令没有设置priority

### ISSUE THREAD

**Issue by liuzj288** [Monarchdos/nonebot_plugin_cloudsign#2]
qd = on_regex("^签到$|^积分$|^(挖矿|我的背包)$|^(钓鱼|我的鱼篓)$|^功能$|^功能 (.*?)$|^领取积分补助$|^签到状态$|^排行榜$|^打劫(.*?)$|^抽奖 (\d+)$|^(出售|售出) ([\u4e00-\u9fa5]+)$|^转账 (\d+)(.*?)$|^(@检查更新@)$|^#(.*?)$|^(猜拳石头|猜拳剪刀|猜拳布) (\d+)$|^(猜数字|我猜) (\d+)$", priority=100, block=True)

**Comment by Monarchdos** [comment]
本插件的指令都是固定的，无如聊天插件等指令冲突的情况，所以没有设置优先级与阻断，下次更新时可以加上。
