### ISSUE TITLE
[Feature] 希望添加探险功能

### ISSUE THREAD

**Issue by Cvandia** [Monarchdos/nonebot_plugin_cloudsign#4]
### 效果: 
- 获得探险奖励，用于兑换积分
        
 - 有几率探险`遇敌`，扣除积分
         
- 探险过程添加随机事件，如：`遇敌人`, `被老鼠夹夹到`（打个比方），让玩家决定是否继续探险，

- 随着探险越深入，风险越大，获得奖励越多

**Comment by Monarchdos** [comment]
很棒的想法，探险功能已经加入。
Use: 
#探险: 购买秘境钥匙开始探险
#探险 前/后/左/右: 秘境开启后进行探险，有四个方向可以走，每个方向都有不同的事件，事件包括发现宝藏(获得积分),遭遇袭击(失去积分),无事发生,退出秘境(结束探索);随着探索的深入风险也会变大。

**Comment by Cvandia** [comment]
> 很棒的想法，探险功能已经加入。 Use: #探险: 购买秘境钥匙开始探险 #探险 前/后/左/右: 秘境开启后进行探险，有四个方向可以走，每个方向都有不同的事件，事件包括发现宝藏(获得积分),遭遇袭击(失去积分),无事发生,退出秘境(结束探索);随着探索的深入风险也会变大。

对了，记得加上`#探险 退出`来实现主动退出探险的效果哦~

**Comment by Cvandia** [comment]
qwq，结束时候，可以显示`本次探险获得积分 -10`

**Comment by Monarchdos** [comment]
> qwq，结束时候，可以显示`本次探险获得积分 -10`

每次行动后都会显示获取或失去了多少积分

**Comment by Monarchdos** [comment]
> 



> > 很棒的想法，探险功能已经加入。 Use: #探险: 购买秘境钥匙开始探险 #探险 前/后/左/右: 秘境开启后进行探险，有四个方向可以走，每个方向都有不同的事件，事件包括发现宝藏(获得积分),遭遇袭击(失去积分),无事发生,退出秘境(结束探索);随着探索的深入风险也会变大。
> 
> 对了，记得加上`#探险 退出`来实现主动退出探险的效果哦~

#探险 退出  功能加入了已经

**Comment by Cvandia** [comment]
> > qwq，结束时候，可以显示`本次探险获得积分 -10`
> 
> 每次行动后都会显示获取或失去了多少积分

最后结束可以统计一下吗？感觉层数多了记不到了自己得了多少分了qwq

**Comment by Monarchdos** [comment]
> > > qwq，结束时候，可以显示`本次探险获得积分 -10`
> > 
> > 
> > 每次行动后都会显示获取或失去了多少积分
> 
> 最后结束可以统计一下吗？感觉层数多了记不到了自己得了多少分了qwq

积分是每行动一步都进行结算的，可以在开始前发送一次积分，结束后再发送一次积分，差值就是自己得了多少分

**Comment by Cvandia** [comment]
> > > > qwq，结束时候，可以显示`本次探险获得积分 -10`
> > > 
> > > 
> > > 每次行动后都会显示获取或失去了多少积分
> > 
> > 最后结束可以统计一下吗？感觉层数多了记不到了自己得了多少分了qwq
> 
> 积分是每行动一步都进行结算的，可以在开始前发送一次积分，结束后再发送一次积分，差值就是自己得了多少分

诶嘞，差不多就这样子的
