### ISSUE TITLE
[Feature] 希望能添加撤回功能

### ISSUE THREAD

**Issue by smoadrareun** [Monarchdos/nonebot_plugin_cloudsign#6]
如果使用的人比较多容易造成刷屏，希望能加入过一段时间主动撤回机器人发送过的消息的功能。

**Comment by Monarchdos** [comment]
这个功能可以通过其他的插件来实现

**Comment by TU-O0T** [comment]
> 这个功能可以通过其他的插件来实现

nonebot商店的撤回插件只能通过回复来撤回消息，在如探险等功能造成大量的消息积压时，这种撤回方式及其麻烦（而且还要把撤回指令再撤回一遍），因此撤回功能最好在插件中实现
