### ISSUE TITLE
签到功能异常，似乎是服务器宕机了

### ISSUE THREAD

**Issue by WhyPilotXia** [Monarchdos/nonebot_plugin_cloudsign#8]
从昨天早上开始，多个IP的多台电脑的机器人签到功能一直异常，怀疑是服务器出了故障

**Comment by Monarchdos** [comment]
修复了已经，某个依赖出了点问题

**Comment by Monarchdos** [comment]
发送”#兑换 2024062021“可以领取补偿积分。

**Comment by WhyPilotXia** [comment]
好的谢谢



---Original---
From: ***@***.***&gt;
Sent at: 2024年6月21日(Fri) Noon11:16
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Monarchdos/nonebot_plugin_cloudsign] 签到功能异常，似乎是服务器宕机了 (Issue #8)




 
发送”#兑换 2024062021“可以领取补偿积分。
